### ISSUE TITLE
Internet Explorer 11 issues

### ISSUE THREAD

**Issue by wilbrm** [BlackrockDigital/startbootstrap-new-age#36]
![1](https://user-images.githubusercontent.com/35427383/34918087-0a06745e-f94e-11e7-80aa-42647186370b.PNG)
![2](https://user-images.githubusercontent.com/35427383/34918088-0a225354-f94e-11e7-96d2-2041cef01e44.PNG)

The site doesnt look good in IE11 unfortunately.

**Comment by davidtmiller** [comment]
Flexbox, gradient font methods, etc. is what is making this not IE11 friendly. Unfortunately I am choosing to just support 'modern browsers' with the themes on Start Bootstrap rather than deal with the headache of making everything backward compatible with old browsers. This theme is a bit more experimental as far as my themes go, so it's a take it or leave it sort of thing here I'm afraid.
