### ISSUE TITLE
concat JS and CSS to improve initial page load speed

### ISSUE THREAD

**Issue by bittlingmayer** [BlackrockDigital/startbootstrap-new-age#42]
The thorough gulp file is highly appreciated this page does very well once caching and gzipping is enabled:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblackrockdigital.github.io%2Fstartbootstrap-new-age%2F

https://tools.pingdom.com/#!/ddPX9I/https://blackrockdigital.github.io/startbootstrap-new-age/

Could it make sense to add a final `concat` step that puts the template-specific and vendor files into one .js file and one .css file?  Or at least those included above the fold?

<img width="1122" alt="screen shot 2018-05-18 at 22 41 53" src="https://user-images.githubusercontent.com/11457984/40252241-cea3c6c2-5aec-11e8-8071-5b9b46672f8a.png">

For one thing, gzip is not efficient for files below 1KB, so on Firebase for example none of these small files are gzipped.

**Comment by davidtmiller** [comment]
I agree that this method will absolutely make the page load faster. The themes here on Start Bootstrap though are more meant to be starting points - and sometimes ready for production, but this is a step in production that I would rather keep up to the end user rather than make as a out-of-the-box feature of the theme itself.

I personally do this for production-level sites, but there are a lot of different ways that people will use these themes in production, and sometimes they won't be using all of the JS or all of the CSS, so (long story ... well ... long) I'd rather keep the concatenation decisions to the end user. Hopefully this explains the closing of this issue!

**Comment by bittlingmayer** [comment]
Fair enough.

Maybe it can be added here without being the default, just to avoid duplication of efforts.
